# Header
menu:
  Home: /
  Archives: /archives
rss: /rss2.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- twitter_feed
- category
- tag
- tagcloud
- archive

# Miscellaneous
google_analytics: UA-74177443-1
favicon: /favicon.ico
twitter: CalebFenton
google_plus:
fb_admins:
fb_app_id:
